lrr <- read.table('C:/Users/Navid/Documents/GitHub/ml-ex1/Rscripts/exampleData/LinearRidgeRegression_MEAN_.1.csv',sep=';')
prr <- read.table('C:/Users/Navid/Documents/GitHub/ml-ex1/Rscripts/exampleData/PolynomialRidgeRegression_MEAN_32_.1.csv',sep=';')
nnr <- read.table('C:/Users/Navid/Documents/GitHub/ml-ex1/Rscripts/exampleData/NearestNeighborsRegression_MEAN_18.csv',sep=';')
nn <- read.table('C:/Users/Navid/Documents/GitHub/ml-ex1/Rscripts/exampleData/NeuralNetwork_1_20.csv',sep=';')
svm <- read.table('C:/Users/Navid/Documents/GitHub/ml-ex1/Rscripts/exampleData/SupportVectorMachine_MEAN.csv',sep=';')
dataframe=data.frame(lrr$V3,nnr$V3,nn$V3,prr$V3,svm$V3)
boxplot(dataframe,xlab='Algorithms',ylab='Difference from the actual MPG',xaxt='no')
axis(1,at=c(1,2,3,4,5),labels=c('LRR', 'PRR','NN', 'Neural Net', 'SVM'))
savehistory('example.R')
dev.copy(png,'myfile.png')
dev.off()