
class Constants(object):
    (MACHINE_LEARNING_METHOD_REGRESSION, MACHINE_LEARNING_METHOD_CLASSIFICATION)=(0,1)
    (MISSING_VALUE_METHOD_NONE, MISSING_VALUE_METHOD_MEAN, MISSING_VALUE_METHOD_MEDIAN, MISSING_VALUE_METHOD_MOST_FREQUENT)=(1, 2, 3, 4)
